name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Скачиваем код репозитория
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Устанавливаем uv и нужную версию Python
    - name: Install uv and Python
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest" # Всегда использовать свежую версию uv
        enable-cache: true # Включаем кэш, чтобы тесты запускались мгновенно
        python-version: "3.14"

    # sync
    - name: Install dependencies
      run: uv sync --frozen

    - name: Run tests
      run: uv run --with pytest pytest
      env:
        TEXT_MODEL: "mock-model"
        VISION_MODEL: "mock-vision-model"

